[package]
name = "libsql_migration"
version = "0.2.2"
edition = "2024"
authors = ["prashant1k99"]
description = "A simple SQL migration tool for libsql databases"
license = "MIT"
repository = "https://github.com/prashant1k99/libsql_migration"
readme = "README.md"
keywords = ["libsql", "sqlite", "migration", "database", "sql"]
categories = ["database", "command-line-utilities"]

[dependencies]
reqwest = { version = "0.12.15", optional = true, features = ["json"] }
# libsql = { path = "./../forks/tursodatabase-libsql/libsql", features = ["sync", "replication"] }
# this is branch ffi-null-pointer-exception pinned to this commit
libsql = { git = "https://github.com/trysoma/tursodatabase-libsql", rev = "25266445e3d3b76ed781d5a7acb82f1ece29c09e", features = ["sync", "replication"] }
serde = { version = "1.0.219", optional = true }
tokio = { version = "1", features = ["rt"] }
serde_json = { version = "1.0.140", optional = true }
tracing = "0.1.43"

[dev-dependencies]
tempfile = "3.10"
tokio = { version = "1", features = ["rt"] }

[features]
default = ["dir"]
dir = []
content = []
remote = ["reqwest", "serde", "serde_json"]

[package.metadata.docs.rs]
all-features = true
